global:
  scrape_interval:     3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'service-collector'
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']