# fly.toml app configuration file generated for pace-surrealdb on 2023-05-20T08:05:42+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pace-surrealdb"
primary_region = "arn"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
