# fly.toml app configuration file generated for spectator-client on 2023-08-01T10:01:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spectator-client"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
