{
 "title": "Pace Websocket Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "OS/Kernel Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_active_bytes" },
    { "expr": "node_memory_free_bytes" }
   ]
  },
  {
   "title": "Node Load (1s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Network I/O (lo0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"lo0\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg by(job, mode) (irate(node_cpu_seconds_total[$__interval]))"
    }
   ]
  },
  { "title": "Websocket metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Location Update Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "location_update_latency" }
   ]
  },
  {
   "title": "Disconnected Clients",
   "type": "timeseries",
   "description": "Number of disconnected clients",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "disconnected_clients" }
   ]
  },
  {
   "title": "Connected clients",
   "type": "timeseries",
   "description": "Number of clients connected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "connected_clients" }
   ]
  },
  {
   "title": "Location Updates Received",
   "type": "timeseries",
   "description": "Number of location updates received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "location_updates_received" }
   ]
  },
  {
   "title": "Location Updates Sent",
   "type": "timeseries",
   "description": "Number of location updates propagated to other clients",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "location_updates_sent" }
   ]
  }
 ]
}