[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
console-subscriber = "0.1.8"
serde = { version = "1.0.130", features = ["derive"] }
config = { version = "0.13" }
thiserror = "1.0.40"
serde_json = "1.0.70"
